trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'installing dependencies'

  - script: npm test
    displayName: 'Running test'
