[build]
  base = ""
  publish = "dist/"
  command = "yarn build"
  environment = { NODE_ENV = "production", NODE_VERSION = "12.x" }

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200